### PR TITLE
Microschema migration fix

### LINKED ISSUE #979: Microschema Migration creates bogus versions
Situation:
* Create microschema
* Link microschema to two projects
* Create nodes in both projects that have micronodes of that microschema
* Update the microschema

Result:
* Bogus versions for the nodes get created. Bogus Draft and Initial edges were also created which reference branches from the other project.

Expected:
* The micronode migration stays in the scope of the project and does not create bogus edges

### LINKED ISSUE #1014: Migration process create multiples containers with the same version
## Gentics Mesh Version, operating system, or hardware.
- v1.4.0

## Operating System
- Linux

## Problem

Got a node with 3 versions (initial published and draft):

image

This node has a micronode field list, in his schema, i update the microschema and the migration process is creating theses versions:

```
{
versions: {
en: [
{
creator: {
uuid: "edb500f303244d6ab500f303247d6a0f"
},
created: "2020-02-21T14:40:43.853Z",
version: "4.1",
draft: true,
published: false,
branchRoot: false
},
{
creator: {
uuid: "edb500f303244d6ab500f303247d6a0f"
},
created: "2020-02-21T14:40:43.847Z",
version: "4.0",
draft: false,
published: true,
branchRoot: false
},
{
creator: {
uuid: "edb500f303244d6ab500f303247d6a0f"
},
created: "2020-02-21T14:40:43.098Z",
version: "4.1",
draft: false,
published: false,
branchRoot: false
},
{
creator: {
uuid: "edb500f303244d6ab500f303247d6a0f"
},
created: "2020-02-21T14:40:43.093Z",
version: "4.0",
draft: false,
published: false,
branchRoot: false
},
{
creator: {
uuid: "edb500f303244d6ab500f303247d6a0f"
},
created: "2020-02-21T14:35:26.101Z",
version: "3.1",
draft: false,
published: false,
branchRoot: false
},
{
creator: {
uuid: "edb500f303244d6ab500f303247d6a0f"
},
created: "2020-02-21T14:35:26.092Z",
version: "3.0",
draft: false,
published: false,
branchRoot: false
},
{
creator: {
uuid: "edb500f303244d6ab500f303247d6a0f"
},
created: "2020-01-07T09:02:05.134Z",
version: "0.1",
draft: false,
published: false,
branchRoot: true
}
]
}
}
```

### LINKED ISSUE #1025: Microschema upgrade is not reliable and can cause rollback to an older node version
## Gentics Mesh Version, operating system, or hardware.
- v1.4.1

## Operating System
- Linux

## JVM
- Oracle JDK 1.8.0_100
- Open JDK 1.8.0_100

## Problem
When upgrading a microschema, we observe some mess in node versions, and under certain circumstance the latest version is rollbacked to an older node version. this can lead to very strange behaviour if we upgrade the microschemas multiples time of unpublished nodes .

## Reproducer

create a schema:
```
{
    "name": "Container",
    "container": false,
    "autoPurge": false,
    "description": "Container",
    "displayField": "name",
    "segmentField": "name",
    "urlFields": [],
    "fields": [
        {
            "name": "containerms",
            "type": "list",
            "label": "containerms",
            "required": false,
            "listType": "micronode",
            "allow": [
                "ContainerMs"
            ]
        },
        {
            "name": "name",
            "type": "string",
            "label": "name",
            "required": false
        }
    ]
}
```
create a microschema:
```
{
    "name": "ContainerMs",
    "description": "ContainerMs v1",
    "fields": [
        {
            "name": "name",
            "type": "string",
            "label": "name",
            "required": false
        }
    ]
}
```
create a node:

Container1 from schema Container
add a field containerMs in his micronode lis

create a copy from Container1

save and publish it in version 1.0
rename it to container2 but dont publish it, let it in draft v 1.1

update ContainerMs description to trigger a node update:

BUG:
container2 got renamed to Container1 (copy)_copy and version is not v1.1 but 0.X

seems that microschema migration is not doing right in node version.

## Expected behaviour and actual behaviour

container2 should stay with name container2

### PR DESCRIPTION
**Pull request by philippguertler**
## Abstract
Fixes microschema migration by fixing the MicroschemaContainerVersionImpl#getDraftFieldContainers method.

Fixes #979 Fixes #1014 Fixes #1025 

### General

* [x] Added abstract that describes the change
* [x] Added changelog entry to `/CHANGELOG.adoc`
* [x] Ensured that the change is covered by tests
* [x] Ensured that the change is documented in the docs

### On API Changes

* [x] Checked if the changes are breaking or not
* [x] Added GraphQL API if applicable
* [x] Added Elasticsearch mapping if applicable

### CODE REVIEW

File: api/src/main/java/com/gentics/mesh/util/VersionNumber.java [hunk 1]
```diff
@@ -166,4 +172,18 @@ public static int versionCompare(String str1, String str2) {
...
+	 * Get the major version part
+	 * @return
+	 */
+	public int getMajor() {
+		return major;
+	}
+
+	/**
+	 * Get the minor version part
+	 */
```
Comment (philippguertler) [inline api/src/main/java/com/gentics/mesh/util/VersionNumber.java:185]:
```suggestion
	/**
	 * Get the minor version part
	 * @return
	 */
```

File: core/src/main/java/com/gentics/mesh/changelog/highlevel/change/FixNodeVersionOrder.java [hunk 2]
```diff
@@ -0,0 +1,191 @@
...
+
+		while (currentContainer != null) {
+			// Since we only look at single branch projects, there can at most only be one next version.
+			NodeGraphFieldContainer nextContainer = Iterables.getFirst(currentContainer.getNextVersions(), null);
+			VersionNumber currentVersion = currentContainer.getVersion();
+			boolean isDuplicate = !seenVersions.add(currentVersion);
+			if (isDuplicate) {
+				currentContainer.remove();
+				if (nextContainer != null) {
+					// previousContainer can't be null because this branch is only visited if there is a duplicate
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/changelog/highlevel/change/FixNodeVersionOrder.java:108]:
```suggestion
					// highestVersion can't be null because this branch is only visited if there is a duplicate
```

File: core/src/main/java/com/gentics/mesh/changelog/highlevel/change/FixNodeVersionOrder.java [hunk 3]
```diff
@@ -0,0 +1,191 @@
...
+				highestVersion = versions.last();
+				currentContainer = nextContainer;
+			}
+		}
+
+		// Reset draft and published edge
+		String branchUuid = initialContent.getBranches(ContainerType.INITIAL).iterator().next();
+		String languageTag = initialContent.getLanguageTag();
+
+		EdgeFrame rawDraftEdge = node.getGraphFieldContainerEdgeFrame(languageTag, branchUuid, ContainerType.DRAFT);
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/changelog/highlevel/change/FixNodeVersionOrder.java:144]: Check draft and published version before loop

File: core/src/main/java/com/gentics/mesh/changelog/highlevel/change/FixNodeVersionOrder.java [hunk 4]
```diff
@@ -0,0 +1,191 @@
...
+		}
+		Tx.get().commit();
+		return mutated;
+	}
+
+	private GraphFieldContainerEdge setNewOutV(GraphFieldContainerEdgeImpl edge, Node from, NodeGraphFieldContainer to) {
+		GraphFieldContainerEdge newEdge = from.addFramedEdge(HAS_FIELD_CONTAINER, to, GraphFieldContainerEdgeImpl.class);
+		newEdge.setBranchUuid(edge.getBranchUuid());
+		newEdge.setLanguageTag(edge.getLanguageTag());
+		newEdge.setSegmentInfo(edge.getSegmentInfo());
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/changelog/highlevel/change/FixNodeVersionOrder.java:170]: This segment info is different for this version, so it has to be recalculated

File: core/src/main/java/com/gentics/mesh/changelog/highlevel/change/FixNodeVersionOrder.java [hunk 5]
```diff
@@ -0,0 +1,191 @@
...
+		newEdge.setType(edge.getType());
+		newEdge.setUrlFieldInfo(edge.getUrlFieldInfo());
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/changelog/highlevel/change/FixNodeVersionOrder.java:172]: Same as above
