### PR TITLE
Graphql name validation and conflict handling

### LINKED ISSUE #597: GraphQL name validation
Query is failing:
```
graphql.AssertException: Name must be non-null, non-empty and match [_A-Za-z][_0-9A-Za-z]*
        at graphql.Assert.assertValidName(Assert.java:57) ~[meshdemo.jar:na]
        at graphql.schema.GraphQLFieldDefinition.<init>(GraphQLFieldDefinition.java:48) ~[meshdemo.jar:na]
        at graphql.schema.GraphQLFieldDefinition$Builder.build(GraphQLFieldDefinition.java:273) ~[meshdemo.jar:na]
        at com.gentics.mesh.graphql.type.field.FieldDefinitionProvider.createMicronodeDef(FieldDefinitionProvider.java:371) ~[meshdemo.jar:na]
        at com.gentics.mesh.graphql.type.field.NodeFieldTypeProvider.generateSchemaFieldType(NodeFieldTypeProvider.java:114) ~[meshdemo.jar:na]
        at com.gentics.mesh.graphql.type.field.NodeFieldTypeProvider.getSchemaFieldsType(NodeFieldTypeProvider.java:43) ~[meshdemo.jar:na]
        at com.gentics.mesh.graphql.type.NodeTypeProvider.createType(NodeTypeProvider.java:387) ~[meshdemo.jar:na]
        at com.gentics.mesh.graphql.type.QueryTypeProvider.getRootSchema(QueryTypeProvider.java:455) ~[meshdemo.jar:na]
        at com.gentics.mesh.graphql.GraphQLHandler.handleQuery(GraphQLHandler.java:57) ~[meshdemo.jar:na]
        at com.gentics.mesh.graphql.GraphQLEndpoint.lambda$registerEndPoints$0(GraphQLEndpoint.java:49) ~[meshdemo.jar:na]
        at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48) ~[meshdemo.jar:na]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273) ~[meshdemo.jar:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[meshdemo.jar:na]
        at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]
```

### PR DESCRIPTION
**Pull request by philippguertler**
Resolves #597

### CODE REVIEW

File: core/src/test/java/com/gentics/mesh/core/schema/MicroschemaEndpointTest.java [hunk 1]
```diff
@@ -447,4 +447,17 @@ public void testDeleteByUUIDWithNoPermission() throws Exception {
 		}
 	}
 
+	@Test
+	public void testConflictingNameWithSchema() throws InterruptedException {
+		MicroschemaCreateRequest microSchemaRequest = new MicroschemaCreateRequest().setName("test");
+		SchemaCreateRequest schemaRequest = new SchemaCreateRequest().setName("test");
+
+		client().createSchema(schemaRequest).blockingAwait();
+		Throwable err = client().createMicroschema(microSchemaRequest).toSingle().test()
```
Comment (philippguertler) [inline core/src/test/java/com/gentics/mesh/core/schema/MicroschemaEndpointTest.java]: Use `call` for error assortion

File: core/src/test/java/com/gentics/mesh/core/schema/SchemaEndpointTest.java [hunk 2]
```diff
@@ -560,4 +557,17 @@ public void testUpdateByUUIDWithoutPerm() throws Exception {
 		call(() -> client().updateSchema(schemaUuid, request), FORBIDDEN, "error_missing_perm", schemaUuid, UPDATE_PERM.getRestPerm().getName());
 	}
 
+	@Test
+	public void testConflictingNameWithMicroschema() throws InterruptedException {
+		MicroschemaCreateRequest microSchemaRequest = new MicroschemaCreateRequest().setName("test");
+		SchemaCreateRequest schemaRequest = new SchemaCreateRequest().setName("test");
+
+		client().createMicroschema(microSchemaRequest).blockingAwait();
+		Throwable err = client().createSchema(schemaRequest).toSingle().test()
```
Comment (philippguertler) [inline core/src/test/java/com/gentics/mesh/core/schema/SchemaEndpointTest.java]: Use `call` for error assortion

File: core/src/test/resources/json/blns.json [hunk 3]
```diff
@@ -0,0 +1,506 @@
...
+  "Dick Van Dyke", 
+  "basement", 
+  "If you're reading this, you've been in a coma for almost 20 years now. We're trying a new technique. We don't know where this message will end up in your dream, but we hope it works. Please wake up, we miss you.", 
+  "Roses are \u001b[0;31mred\u001b[0m, violets are \u001b[0;34mblue. Hope you enjoy terminal hue", 
+  "But now...\u001b[20Cfor my greatest trick...\u001b[8m", 
+  "The quic\b\b\b\b\b\bk brown fo\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007\u0007x... [Beeeep]", 
+  "Powerلُلُصّبُلُلصّبُررً ॣ ॣh ॣ ॣ冗", 
+  "🏳0🌈️", 
+  "జ్ఞ‌ా"
+]
```
Comment (philippguertler) [inline core/src/test/resources/json/blns.json]: Shorten list
