### PR TITLE
Make index sync at startup non blocking

### LINKED ISSUE #862: Don't block Mesh startup when index sync fails
In some cases a forced index sync is being invoked. This will cause the reindex action in BootstrapInitializerImpl. This action will block until all documents have been synced. This will stall the startup process if ES is broken / unreachable. We should not block the startup in this case.

### PR DESCRIPTION
**Pull request by philippguertler**
Fixes #862

### CODE REVIEW

File: core/src/main/java/com/gentics/mesh/cli/BootstrapInitializerImpl.java [hunk 1]
```diff
@@ -185,9 +185,7 @@
 			return;
 		}
 		// Ensure indices are setup and sync the documents
-		log.info("Invoking index sync. This may take some time..");
```
Comment (Jotschi) [inline core/src/main/java/com/gentics/mesh/cli/BootstrapInitializerImpl.java]: Why did you remove this logging stuff?
