### PR TITLE
Fix allow property reset handling. Fixes #663

### LINKED ISSUE #663: Schemafield allow property not resettable
## Gentics Mesh Version, operating system, or hardware.
0.28.2 running in docker-compose https://github.com/gentics/mesh-compose

## Operating System
MacOS 10.14.3 (18D109)

## Problem
Regarding Mesh REST API endpoint: ```POST /schemas/schemaUuid```:

### Current Behavior (sequence):

1. Request payload schema.fields[0]: ```type: string``` and ```allow``` not in payload
Result: all strings allowed.

2. Request payload schema.fields[0]: ```type: string``` and ```allow: [ 'foo', 'bar' ]```
Result: only strings 'foo' and 'bar' allowed.

3. Intention: no allow limitation at all.
Request payload schema.fields[0]: ```type: string``` and ```allow``` not in payload
Result: still only strings 'foo' and 'bar' allowed.

4. Intention: no allow limitation at all.
Request payload schema.fields[0]: ```type: string``` and ```allow: []```
Result: no strings **at all** allowed.

### Expected Behavior:

4. Intention: no allow limitation at all.
```type: string``` and ```allow: []```
Result: all strings allowed.

### PR DESCRIPTION
**Pull request by Jotschi**

### CODE REVIEW

File: core/src/test/java/com/gentics/mesh/core/schema/field/string/StringFieldEndpointTest.java [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+		nodeUpdateRequest.getFields().put("extraString", FieldUtil.createStringField("someValue"));
+		call(() -> client().updateNode(projectName(), nodeUuid, nodeUpdateRequest), BAD_REQUEST, "node_error_invalid_string_field_value",
+			"extraString",
+			"someValue");
+
+		// 3. Update the schema again with empty allowed valued
+		request.removeField("extraString");
+		request.addField(new StringFieldSchemaImpl().setAllowedValues().setName("extraString"));
+
+		call(() -> client().updateNode(projectName(), nodeUuid, nodeUpdateRequest), BAD_REQUEST, "node_error_invalid_string_field_value",
```
Comment (npomaroli) [inline core/src/test/java/com/gentics/mesh/core/schema/field/string/StringFieldEndpointTest.java]: Don't check bad request again
