### PR TITLE
Fix ETag generation issue - Fixes #881

### LINKED ISSUE #881: Saving the permission matrix of roles is not properly working
## Gentics Mesh Version, operating system, or hardware.
- v0.40.3

## Operating System
- Linux (Docker-compose from website)

## Problem

Whenever I update the permission of my roles and refresh the page they automatically get dumped and everything is empty again.

### Expected

When I update the permissions of a role the view should reflect those changes and save the permissions to the store.

### Actual

After a refresh the whole permission matrix is empty again and you need to set everything again.

I'm unsure whether the changes have actually been saved.

### PR DESCRIPTION
**Pull request by Jotschi**

### CODE REVIEW

File: core/src/main/java/com/gentics/mesh/core/data/generic/AbstractMeshCoreVertex.java [hunk 1]
```diff
@@ -167,6 +170,32 @@ public String getETag(InternalActionContext ac) {
...
+				Set<String> humanNames = new HashSet<>();
+				for (GraphPermission permission : permSet) {
+					humanNames.add(permission.getRestPerm().getName());
+				}
+				String[] names = humanNames.toArray(new String[humanNames.size()]);
+				keyBuilder.append(Arrays.toString(names));
+			}
+
+		}
+
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/core/data/generic/AbstractMeshCoreVertex.java]: Create a new abstract method to get the etag information for the concrete class. Call it here and combine it with the generic etag information. This guarantees that the generic information will not be forgotten.

File: core/src/main/java/com/gentics/mesh/core/data/impl/BranchImpl.java [hunk 2]
```diff
@@ -524,8 +524,8 @@ public boolean contains(MicroschemaContainerVersion microschemaContainerVersion)
 	}
 
 	@Override
-	public String getETag(InternalActionContext ac) {
-		return ETag.hash(getUuid() + "-" + getLastEditedTimestamp());
+	public String getSubETag(InternalActionContext ac) {
+		return ETag.hash(String.valueOf(getLastEditedTimestamp()));
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/core/data/impl/BranchImpl.java]: Remove hash

File: core/src/main/java/com/gentics/mesh/core/data/impl/ProjectImpl.java [hunk 3]
```diff
@@ -294,8 +294,10 @@ public BranchRoot getBranchRoot() {
 	}
 
 	@Override
-	public String getETag(InternalActionContext ac) {
-		return ETag.hash(getUuid() + "-" + getLastEditedTimestamp());
+	public String getSubETag(InternalActionContext ac) {
+		StringBuilder keyBuilder = new StringBuilder();
+		keyBuilder.append(getLastEditedTimestamp());
+		return ETag.hash(keyBuilder);
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/core/data/impl/ProjectImpl.java]: Remove hash

File: core/src/main/java/com/gentics/mesh/core/data/impl/RoleImpl.java [hunk 4]
```diff
@@ -205,9 +205,8 @@ public boolean update(InternalActionContext ac, EventQueueBatch batch) {
 	}
 
 	@Override
-	public String getETag(InternalActionContext ac) {
+	public String getSubETag(InternalActionContext ac) {
 		StringBuilder keyBuilder = new StringBuilder();
-		keyBuilder.append(super.getETag(ac));
 		keyBuilder.append(getLastEditedTimestamp());
 		return ETag.hash(keyBuilder);
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/core/data/impl/RoleImpl.java]: Remove hash

File: core/src/main/java/com/gentics/mesh/core/data/impl/TagFamilyImpl.java [hunk 5]
```diff
@@ -227,9 +227,8 @@ public void applyPermissions(EventQueueBatch batch, Role role, boolean recursive
 	}
 
 	@Override
-	public String getETag(InternalActionContext ac) {
+	public String getSubETag(InternalActionContext ac) {
 		StringBuilder keyBuilder = new StringBuilder();
-		keyBuilder.append(super.getETag(ac));
 		keyBuilder.append(getLastEditedTimestamp());
 		return ETag.hash(keyBuilder);
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/core/data/impl/TagFamilyImpl.java]: Remove hash

File: core/src/main/java/com/gentics/mesh/core/data/impl/TagImpl.java [hunk 6]
```diff
@@ -262,9 +262,8 @@ public boolean update(InternalActionContext ac, EventQueueBatch batch) {
 	}
 
 	@Override
-	public String getETag(InternalActionContext ac) {
+	public String getSubETag(InternalActionContext ac) {
 		StringBuilder keyBuilder = new StringBuilder();
-		keyBuilder.append(super.getETag(ac));
 		keyBuilder.append(getLastEditedTimestamp());
 		keyBuilder.append(ac.getBranch(getProject()).getUuid());
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/core/data/impl/TagImpl.java]: Remove hash

File: core/src/main/java/com/gentics/mesh/core/data/impl/UserImpl.java [hunk 7]
```diff
@@ -649,9 +649,8 @@ public boolean update(InternalActionContext ac, EventQueueBatch batch) {
 	}
 
 	@Override
-	public String getETag(InternalActionContext ac) {
+	public String getSubETag(InternalActionContext ac) {
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/core/data/impl/UserImpl.java]: Remove hash

File: core/src/main/java/com/gentics/mesh/core/data/job/impl/JobImpl.java [hunk 8]
```diff
@@ -138,8 +138,8 @@ public void setWarnings(JobWarningList warnings) {
 	}
 
 	@Override
-	public String getETag(InternalActionContext ac) {
-		return ETag.hash(getUuid() + getErrorMessage() + getErrorDetail());
+	public String getSubETag(InternalActionContext ac) {
+		return ETag.hash(getErrorMessage() + getErrorDetail());
```
Comment (philippguertler) [inline core/src/main/java/com/gentics/mesh/core/data/job/impl/JobImpl.java]: Remove hash
